=== notzilly/php_xml/GioMovies.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT filmes (filme)*>
<!ELEMENT filme (tituloEN, tituloBR, genero, duracao, ano, site, distribuicao, direcao, (elenco|elencoApoio)*, sinopse)>
<!ATTLIST filme
    id ID #REQUIRED
>
<!ELEMENT tituloEN (#PCDATA)>
<!ELEMENT tituloBR (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracao (#PCDATA)>
<!ELEMENT ano (#PCDATA)>
<!ELEMENT site (#PCDATA)>
<!ELEMENT distribuicao (#PCDATA)>
<!ELEMENT direcao (#PCDATA)>
<!ELEMENT elenco (#PCDATA)>
<!ELEMENT elencoApoio (#PCDATA)>
<!ELEMENT sinopse (#PCDATA)>

=== notzilly/php_xml/input_GioMovies_EncodingISO88591.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE filmes SYSTEM "GioMovies.dtd">
<filmes>
    <filme id="starwarsIV">
        <tituloEN>Star Wars</tituloEN>
        <tituloBR>Guerra nas Estrelas</tituloBR>
        <genero>Aventura/Ficção Científica</genero>
        <duracao>121</duracao>
        <ano>1977</ano>
        <site>http://www.starwars.com/episode-iv </site>
        <distribuicao>20th Century Fox Film Corporation</distribuicao>
        <direcao>George Lucas</direcao>
        <elenco>Mark Hamill</elenco>
        <elenco>Harrison Ford</elenco>
        <elenco>Carrie Fisher</elenco>
        <sinopse>Luke Skywalker (Mark Hammil) sonha ir para a Academia como seus amigos, mas se vê envolvido em uma guerra intergalática quando seu tio compra dois robôs e com eles encontra uma mensagem da princesa Leia Organa (Carrie Fisher) para o jedi Obi-Wan Kenobi (Alec Guiness) sobre os planos da construção da Estrela da Morte, uma gigantesca estação espacial com capacidade para destruir um planeta. Luke então se junta aos cavaleiros jedi e a Hans Solo (Harrison Ford), um mercenário, e junto com membros da resistência tentam destruir esta terrível ameaça.</sinopse>
    </filme>
    <filme id="armageddon">
        <tituloEN>Armageddon</tituloEN>
        <tituloBR>Armageddon</tituloBR>
        <genero>Ficção Científica</genero>
        <duracao>151</duracao>
        <ano>1998</ano>
        <site>http://movies.go.com/armageddon</site>
        <distribuicao>Buena Vista Pictures / Touchstone Pictures</distribuicao>
        <direcao>Michael Bay</direcao>
        <elenco>Bruce Willis</elenco>
        <elenco>Ben Affleck</elenco>
        <elencoApoio>Billy Bob Thornton</elencoApoio>
        <elenco>Liv Tyler</elenco>
        <sinopse>Após uma chuva de pequenos meteoros que atingem a Terra (incluindo Nova York), a NASA se dá conta de que um asteróide do tamanho do Texas está em um curso de colisão com o nosso planeta. O asteróide se aproxima da Terra à uma velocidade 35.000km/h. e, se o choque acontecer, qualquer forma de vida deixará de existir na Terra, exatamente como o que exterminou os dinossauros 65 milhões de anos atrás. Restando apenas 18 dias para o choque entre a Terra e o asteróide, a única solução possível é enviar astronautas em um ônibus espacial até a superfície do asteróide e lá perfurar 800 pés para colocar um bomba nuclear, detonando-a por controle remoto. Para cumprir tal missão é convocado o mais famoso perfurador de petróleo (Bruce Willis) a grandes profundidades do mundo, que exige formar sua equipe com técnicos que têm um comportamento nada convencional para os padrões do governo.
</sinopse>
    </filme>
    <filme id="patriota">
        <tituloEN>The Patriot</tituloEN>
        <tituloBR>O Patriota</tituloBR>
        <genero>Drama</genero>
        <duracao>164</duracao>
        <ano>2000</ano>
        <site>http://www.thepatriot.com</site>
        <distribuicao>Columbia TriStar / Sony Pictures Entertainment</distribuicao>
        <direcao>Rolland Emmerich</direcao>
        <elenco>Mel Gibson</elenco>
        <elenco>Heath Ledger</elenco>
        <elenco>Joely Richardson</elenco>
        <elenco>Jason Isaacs</elenco>
        <sinopse>Benjamin Martin (Mel Gibson) é um herói do violento conflito entre França e Índia. Desde o término da guerra, ele renunciou a luta e resolveu viver em paz com sua família. Mas quando os ingleses levam a guerra da independência americana para dentro de sua casa, Benjamin não vê outra saída a não ser pegar nas armas novamente, desta vez acompanhado por seu filho idealista (Heath Ledger), e liderar uma brava rebelião em uma batalha contra o implacável e equipado exército britânico. Neste processo, ele descobre que o único meio de proteger sua família é lutando pela liberdade da jovem nação.</sinopse>
    </filme>
    <filme id="apollo13">
        <tituloEN>Apollo 13</tituloEN>
        <tituloBR>Apollo 13</tituloBR>
        <genero>Drama </genero>
        <duracao>138</duracao>
        <ano>1995</ano>
        <site/>
        <distribuicao>Universal Pictures / Imagine Entertainment</distribuicao>
        <direcao>Ron Howard</direcao>
        <elenco>Tom Hanks</elenco>
        <elenco>Bill Paxton</elenco>
        <elenco>Kevin Bacon</elenco>
        <elenco>Ed Harris</elenco>
        <sinopse>Três astronautas americanos a caminho de uma missão na Lua sobrevivem à uma explosão, mas precisam retornar rapidamente à Terra para poderem sobreviver, pois correm o risco de ficarem sem oxigênio. Além disto existe o risco de, mesmo retornando, a nave ficar seriamente danificada, por não suportar o imenso calor na reentrada da órbita terrestre.</sinopse>
    </filme>
    <filme id="cem-garotas">
        <tituloEN>100 Girls</tituloEN>
        <tituloBR>100 Garotas</tituloBR>
        <genero>Comédia</genero>
        <duracao/>
        <ano>2000</ano>
        <site>http://www.100girls.net</site>
        <distribuicao>Dream Entertainment, Inc. / Michael/Finney Productions</distribuicao>
        <direcao>Michael Davis</direcao>
        <elenco>Jonathan Tucker</elenco>
        <elenco>Larisa Oleynik</elenco>
        <elenco>Emmanuelle Chriqui</elenco>
        <elenco>Jaime Pressly</elenco>
        <sinopse>Calouro de faculdade (Jonathan Tucker) encontra a garota de seus sonhos durante um blecaute dentro do elevador. Ele não vê seu rosto, mas se apaixona instantaneamente por ela. Pela manhã, ela desaparece e ele inicia uma busca, que se exstende ao longo do semestre.</sinopse>
    </filme>
    <filme id="sextosentido">
        <tituloEN>The Sixth Sense</tituloEN>
        <tituloBR>O Sexto Sentido</tituloBR>
        <genero>Suspense</genero>
        <duracao>106</duracao>
        <ano>1999</ano>
        <site>http://www.studio.go.com/movies/sixthsense</site>
        <distribuicao>Buena Vista International</distribuicao>
        <direcao>M. Night Shyamalan</direcao>
        <elenco>Haley Joel Osment</elenco>
        <elenco>Bruce Willis</elenco>
        <elencoApoio>Toni Collette</elencoApoio>
        <elencoApoio>Olivia Williams</elencoApoio>
        <sinopse>O psicólogo infantil Malcolm Crowe (Bruce Willis) abraça com dedicação o caso de Cole Sear (Haley Joel Osment). O garoto, de 8 anos, tem dificuldades de entrosamento no colégio e vive paralisado de medo. Malcolm, por sua vez, busca se recuperar de um trauma sofrido anos antes, quando um de seus pacientes se suicidou na sua frente.</sinopse>
    </filme>
    <filme id="eueumesmoeirene">
        <tituloEN>Me, Myself And Irene</tituloEN>
        <tituloBR>Eu, Eu Mesmo e Irene</tituloBR>
        <genero>Comédia</genero>
        <duracao>116</duracao>
        <ano>2000</ano>
        <site>http://www.memyselfandirene.com</site>
        <distribuicao>20th Century Fox Film Corporation</distribuicao>
        <direcao>Bobby Farrelly e Peter Farrelly</direcao>
        <elenco>Jim Carrey</elenco>
        <elenco>Renée Zellweger</elenco>
        <elencoApoio>Chris Cooper</elencoApoio>
        <elencoApoio>Michael Bowman</elencoApoio>
        <sinopse>Charlie (Jim Carrey) faz parte da força policial de Rhode Island há 17 anos. Trabalhador, honesto, pai de três filhos e sempre disposto a ajudar, Charlie é amado por todos à sua volta. Mas ele tem um problema: sofre da Síndrome de Dupla Personalidade. Se deixar de tomar seus remédios, sua segunda personalidade, Harry, vem à tona. Harry não tem nada em comum com Charlie: é beberrão, agressivo e grosso com todos. Até que ambos conhecem e se apaixonam por Irene Waters (Renée Zellweger) e passam a lutar consigo mesmo para terem o domínio do mesmo corpo.</sinopse>
    </filme>
    <filme id="americanpie2">
        <tituloEN>American Pie 2</tituloEN>
        <tituloBR>American Pie 2</tituloBR>
        <genero>Comédia</genero>
        <duracao>104</duracao>
        <ano>2001</ano>
        <site>http://www.americanpiemovie.com</site>
        <distribuicao>Universal Pictures</distribuicao>
        <direcao>James B. Rogers</direcao>
        <elenco>Jason Biggs</elenco>
        <elenco>Jennifer Coolidge</elenco>
        <elenco>Shannon Elizabeth</elenco>
        <elencoApoio>Alyson Hannigan</elencoApoio>
        <sinopse>Ao término do primeiro ano da faculdade, Jim (Jason Biggs), Oz (Chris Klein), Kevin (Thomas Ian Nicholas), Stifler (Seann William Scott) e Finch (Eddie Kaye Thomas) mais uma vez se reencontram. Mas agora Nadia (Shannon Elizabeth) está prestes a vir visitar Jim, que ainda não se sente preparado sexualmente para encontrá-la e receberá a ajuda dos amigos. </sinopse>
    </filme>
    <filme id="mafianodiva">
        <tituloEN>Analyze This</tituloEN>
        <tituloBR>Máfia no Divã</tituloBR>
        <genero>Comédia</genero>
        <duracao>104</duracao>
        <ano>1999</ano>
        <site/>
        <distribuicao>Warner Bros</distribuicao>
        <direcao>Harold Ramis</direcao>
        <elenco>Robert De Niro</elenco>
        <elenco>Billy Crystal</elenco>
        <elenco>Lisa Kudrow</elenco>
        <elencoApoio>Chazz Palminteri</elencoApoio>
        <sinopse>Paul Vitti (Robert De Niro), o chefe de uma "família", tem repentinamente ataques de ansiedade por causa de problemas do passado. Assim, decide consultar secretamente Ben Sobel (Billy Crystal), um psiquiatra, pois se a história se espalhar vão dizer que ele está "frouxo". Mas o pior é que Vitti deseja estar curado em apenas duas semanas, quando acontecerá um grande reunião da Máfia, e Sobel está viajando para Miami, onde pretende se casar com Laura MacNamara (Lisa Kudrow). Vitti é o tipo de pessoa que está acostumado em ter qualquer pessoa que trabalhe para ele a disposição vinte e quatro horas por dia, assim Sobel passa a ser "requisitado" pelos capangas de Vitti nos horários e lugares mais impróprios, inclusive na hora de seu casamento. Paralelamente, os agentes federais até forjam provas para que Sobel torne-se seu informante e diga quando e aonde será esta reunião das "famílias". </sinopse>
    </filme>
    <filme id="starwarsV">
